### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BMwanza** [luke-hawk/nativescript-store-ratings#1]
Is it possible to get a response from the API call to see if the user submitted a rating or not? That way, if a user did submit a rating I can set a `boolean` to not prompt that user again.

**Comment by luke-hawk** [comment]
Hi @BMwanza, as far as I know there is know way of getting a response to know whether a user submitted and what rating it was. It's all handled by the native SDKs. However, you don't have to worry about your users getting prompted more than once as the native SDKs also cover that out of the box. In other words, it's not even possible to prompt a user again after they have submitted a response. Only in development you will see the prompt being initialized everytime you call `storeRating.initRating()`.

**Comment by BMwanza** [comment]
Hi @luke-hawk 

Ah, nice that's fantastic good to know that the SDKs handle that case while in production mode.

That said then how does this plugin determine if the env is running development or production? In other words how can ensure that the plugin recognizes when the app is being run as production or as development?

Appreciate all your help and work towards this plugin

**Comment by BMwanza** [comment]
@luke-hawk Follow Up: Reason why I ask is because despite running the `ns run android --release` command which builds and runs a release build, the rating prompt still did not appear on Android.

I have yet to test with a release build on ios as I am having unreleated Xcode issues.

**Comment by luke-hawk** [comment]
Sorry for the late response. It seems like it only pops up when the app has been downloaded from google play.
